name:                Emerald
version:             0.0.0.0
github:              "emerald/TEmPLE"
license:             BSD3
author:              "Oleks Shturmov"
maintainer:          "oleks@oleks.info"
copyright:           "Oleks Shturmov &lt;oleks@oleks.info&gt;"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            The new Emerald Compiler and Runtime
category:            Compilers/Interpreters

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/emerald/TEmPLE#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - GenericPretty >= 1.2.2
  - prettyprinter >= 1.2.1

executables:
  emerald:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - Emerald
    - GenericPretty >= 1.2.2

tests:
  Emerald-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - Emerald
    - GenericPretty >= 1.2.1
    - MissingH >= 1.4.1.0
    - directory >= 1.3.3.0
    - filepath >= 1.4.2.1
    - tasty
    - tasty-hspec >= 1.1
    - tasty-golden >= 2.3.2
    - tasty-quickcheck
