name:                Emerald
version:             0.1.0.0
github:              "emerald/emerald"
license:             BSD3
author:              "Oleks Shturmov"
maintainer:          "oleks@oleks.info"
copyright:           "Oleks Shturmov &lt;oleks@oleks.info&gt;"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            The new Emerald Compiler and Runtime
category:            Compilers/Interpreters

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/emerald/emerald#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Emerald-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Emerald

tests:
  Emerald-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Emerald
    - tasty
    - tasty-hspec
    - tasty-quickcheck
